"""Proves the ffmpeg contract against real ffmpeg. Synthesises its own inputs.

Every other test in this suite replaces the subprocess with a fake, so until now
nothing established that the argv `build_encode_command` assembles is argv real
ffmpeg accepts, nor that the flags do what their names claim. This module runs
it for real and reads the result back with ffprobe.

No network. The tone and the artwork are generated by ffmpeg's own `lavfi`, so
the fixtures are built in a fraction of a second and committed to nothing.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, NamedTuple

import pytest

from memill.config import VbrQuality
from memill.encoder import build_encode_command, run_encode
from memill.naming import TrackTags

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg and ffprobe are required for the end-to-end proof",
)

SOURCE_URL = "https://example.test/watch?v=1"
_MEAN_VOLUME = re.compile(r"mean_volume:\s*(-?\d+(?:\.\d+)?) dB")


def _ffmpeg(*args: str, loglevel: str = "error") -> str:
    """Run ffmpeg to completion and return its stderr, where it files reports.

    `loglevel` is a parameter because the filters that measure a file --
    volumedetect above all -- print their summary at info level and are
    invisible at the error level the fixture synthesis wants.
    """
    completed = subprocess.run(
        ["ffmpeg", "-nostdin", "-y", "-loglevel", loglevel, *args],
        capture_output=True,
        text=True,
        check=True,
    )
    return completed.stderr


def _probe(path: Path) -> dict[str, Any]:
    completed = subprocess.run(
        [
            "ffprobe",
            "-v",
            "quiet",
            "-print_format",
            "json",
            "-show_format",
            "-show_streams",
            str(path),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    parsed: dict[str, Any] = json.loads(completed.stdout)
    return parsed


def _pixel(path: Path, x: int, y: int) -> tuple[int, int, int]:
    """Return one RGB pixel of the picture attached to `path`."""
    completed = subprocess.run(
        [
            "ffmpeg",
            "-nostdin",
            "-v",
            "error",
            "-i",
            str(path),
            "-map",
            "0:v:0",
            "-frames:v",
            "1",
            "-vf",
            f"crop=1:1:{x}:{y}",
            "-f",
            "rawvideo",
            "-pix_fmt",
            "rgb24",
            "-",
        ],
        capture_output=True,
        check=True,
    )
    raw = completed.stdout[:3]
    assert len(raw) == 3, f"expected 3 bytes of rgb24, got {completed.stdout!r}"
    red, green, blue = raw
    return red, green, blue


def _mean_volume(path: Path) -> float:
    """Return the mean volume of `path` in dBFS."""
    report = _ffmpeg(
        "-i", str(path), "-af", "volumedetect", "-f", "null", "-", loglevel="info"
    )
    match = _MEAN_VOLUME.search(report)
    assert match is not None, f"volumedetect reported no mean_volume:\n{report}"
    return float(match.group(1))


class Encoded(NamedTuple):
    path: Path
    progress: list[float]


@pytest.fixture(scope="module")
def encoded(tmp_path_factory: pytest.TempPathFactory) -> Encoded:
    """One real encode of a synthesised tone and a synthesised 16:9 thumbnail."""
    work = tmp_path_factory.mktemp("end-to-end")
    audio = work / "tone.mp3"
    cover = work / "cover.png"
    output = work / "out.mp3"

    # Deliberately tagged, and deliberately not a bare WAV. What yt-dlp hands
    # over arrives tagged by whoever uploaded it, and `-map_metadata -1` is the
    # flag that stops that leaking into the library -- a metadata-free source
    # makes it unobservable, so the fixture supplies metadata to be stripped.
    _ffmpeg(
        "-f", "lavfi", "-i", "sine=frequency=440:duration=3",
        "-c:a", "libmp3lame", "-q:a", "5",
        "-metadata", "genre=Leakage",
        "-metadata", "composer=Nobody",
        str(audio),
    )  # fmt: skip
    # 640x360, red margins around a blue centre. Centre-cropping keeps only the
    # blue; scaling alone would squash the red margins in. A plain "is it
    # square?" assertion cannot tell those apart, because scale=600:600 forces
    # a square whether the crop ran or not -- so the colours are the evidence,
    # and this fixture exists to make them differ.
    #
    # The blue is 440 wide, not the 360 the crop takes. Sizing it to exactly
    # the crop width would put the assertion on a zero-slack boundary, one
    # pixel of rounding away from reading a red edge for the wrong reason;
    # 440 leaves 40px of margin on each side of the 360-wide centred crop.
    _ffmpeg(
        "-f", "lavfi", "-i", "color=c=red:s=100x360",
        "-f", "lavfi", "-i", "color=c=blue:s=440x360",
        "-f", "lavfi", "-i", "color=c=red:s=100x360",
        "-filter_complex", "[0:v][1:v][2:v]hstack=inputs=3",
        "-frames:v", "1", str(cover),
    )  # fmt: skip

    progress: list[float] = []
    run_encode(
        build_encode_command(
            audio=audio,
            output=output,
            quality=VbrQuality(5),
            tags=TrackTags(
                title="Test Tone",
                artist="Tester",
                album="Fixtures",
                year="2026",
                source_url=SOURCE_URL,
            ),
            cover=cover,
        ),
        duration=3.0,
        on_progress=progress.append,
    )
    return Encoded(output, progress)


def test_a_real_encode_carries_tags_and_embedded_artwork(encoded: Encoded) -> None:
    probed = _probe(encoded.path)
    tags = {key.lower(): value for key, value in probed["format"]["tags"].items()}
    assert tags["title"] == "Test Tone"
    assert tags["artist"] == "Tester"
    assert tags["album"] == "Fixtures"
    assert tags["date"] == "2026"
    assert tags["comment"] == SOURCE_URL
    # The source carried these. `-map_metadata -1` is why they are gone.
    assert "genre" not in tags, "source metadata survived -map_metadata -1"
    assert "composer" not in tags, "source metadata survived -map_metadata -1"

    audio_streams = [s for s in probed["streams"] if s["codec_type"] == "audio"]
    video_streams = [s for s in probed["streams"] if s["codec_type"] == "video"]
    assert len(audio_streams) == 1
    assert len(video_streams) == 1
    assert audio_streams[0]["codec_name"] == "mp3"

    cover = video_streams[0]
    assert cover["codec_name"] == "mjpeg"
    assert cover["disposition"]["attached_pic"] == 1
    # A literal, deliberately not encoder.COVER_SIZE: importing the constant
    # would make this assertion move with any change to it and assert nothing.
    assert (cover["width"], cover["height"]) == (600, 600)
    # The stream-level tags are what makes a player show this as front cover
    # art rather than as a one-frame video track it offers to play.
    assert cover["tags"]["comment"] == "Cover (front)"


def test_the_cover_is_centre_cropped_and_not_squashed(encoded: Encoded) -> None:
    """The top-left of the artwork is blue, so the red margins were cropped."""
    red, _green, blue = _pixel(encoded.path, 0, 0)
    assert blue > 200, f"top-left pixel is not blue: {_pixel(encoded.path, 0, 0)}"
    assert red < 60, "red margin survived, so the centre-crop did not run"


def test_the_id3_envelope_is_v2_3_with_a_v1_trailer(encoded: Encoded) -> None:
    """ID3v2.3 with a v1 trailer, which is what old players still read.

    ffprobe reports the tag *values* whichever version wrote them, so the only
    way to see which envelope was used is to read the bytes.
    """
    raw = encoded.path.read_bytes()
    assert raw[:3] == b"ID3"
    assert raw[3] == 3, f"ID3v2 major version is {raw[3]}, wanted 3"
    assert raw[-128:-125] == b"TAG", "no ID3v1 trailer, so -write_id3v1 did not run"


def test_progress_is_parsed_from_real_ffmpeg_and_reaches_completion(
    encoded: Encoded,
) -> None:
    assert encoded.progress, "ffmpeg emitted nothing run_encode could parse"
    # More than one, because every other assertion here is satisfied by a bare
    # [1.0] -- which is what an implementation that parsed only `progress=end`
    # and ignored out_time_us entirely would produce. Intermediate samples are
    # the whole point of streaming the pipe; three arrive for this encode.
    assert len(encoded.progress) > 1, f"only terminal progress: {encoded.progress}"
    assert all(0.0 <= fraction <= 1.0 for fraction in encoded.progress)
    assert encoded.progress == sorted(encoded.progress)
    assert encoded.progress[-1] == 1.0


def test_a_muxed_source_contributes_only_its_audio(tmp_path: Path) -> None:
    """`-map 0:a:0`, not `-map 0`: a source carrying video must not add it.

    yt-dlp is asked for an audio-only stream, so this should not arrive -- but
    if it ever does, the cover must remain the only picture in the file, and a
    bare `-map 0` would instead leave two video streams in the MP3.
    """
    source = tmp_path / "muxed.mkv"
    cover = tmp_path / "cover.png"
    output = tmp_path / "out.mp3"
    # mpeg4, not libx264: a native encoder is present in every ffmpeg build,
    # so this fixture cannot fail for want of an external library.
    _ffmpeg(
        "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
        "-f", "lavfi", "-i", "color=c=green:s=320x240:d=2:r=10",
        "-map", "0:a", "-map", "1:v",
        "-c:a", "libmp3lame", "-q:a", "5", "-c:v", "mpeg4",
        str(source),
    )  # fmt: skip
    _ffmpeg(
        "-f", "lavfi", "-i", "color=c=blue:s=640x360", "-frames:v", "1", str(cover)
    )

    run_encode(
        build_encode_command(
            audio=source,
            output=output,
            quality=VbrQuality(5),
            tags=TrackTags(title="Muxed"),
            cover=cover,
        ),
        duration=2.0,
    )

    streams = _probe(output)["streams"]
    kinds = [stream["codec_type"] for stream in streams]
    assert kinds.count("audio") == 1
    assert kinds.count("video") == 1, f"the source video came along too: {kinds}"


def test_normalize_moves_the_level_to_the_loudnorm_target(tmp_path: Path) -> None:
    audio = tmp_path / "tone.wav"
    _ffmpeg("-f", "lavfi", "-i", "sine=frequency=440:duration=3", str(audio))

    def encode(name: str, *, normalize: bool) -> Path:
        output = tmp_path / name
        run_encode(
            build_encode_command(
                audio=audio,
                output=output,
                quality=VbrQuality(5),
                tags=TrackTags(title="Loud"),
                normalize=normalize,
            ),
            duration=3.0,
        )
        return output

    plain = encode("plain.mp3", normalize=False)
    normalized = encode("normalized.mp3", normalize=True)

    assert float(_probe(normalized)["format"]["duration"]) > 2.0

    # loudnorm=I=-14 lands this tone at -13.3 dBFS on ffmpeg 4.4, repeatably.
    # The band is deliberately loose: it still excludes the -23.3 and -4.5 that
    # I=-24 and I=-5 measure at, so a retarget cannot hide in it, while leaving
    # ~6 dB of room for a future ffmpeg changing single-pass loudnorm slightly.
    # The exact target is pinned as a literal in test_encoder.py, which does
    # not need ffmpeg and therefore never skips.
    assert -20.0 < _mean_volume(normalized) < -8.0
    # And it moved: an ignored --normalize would produce two identical files.
    assert _mean_volume(normalized) - _mean_volume(plain) > 3.0
